import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TranslationsProvider from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TranslationsProvider>
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
